name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build API Docker Image
      working-directory: src
      run: docker build LiatrioPoC.Api -t liatriocorekjpoc.azurecr.io/liatriopocapi:latest
    - name: Build Web Docker Image
      working-directory: src
      run: docker build LiatrioPoC.Web -t liatriocorekjpoc.azurecr.io/liatriopocweb:latest
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    - name: Push API Container Image
      run: docker push liatriocorekjpoc.azurecr.io/liatriopocapi
    - name: Push Web Container Image
      run: docker push liatriocorekjpoc.azurecr.io/liatriopocweb
