name: Build & Deploy API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Web Docker Image
      working-directory: src
      run: docker build . -f LiatrioPoC.Api/Dockerfile -t liatriocorekjpoc.azurecr.io/liatriopocapi:1.0.${{ github.run_number }}
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    - name: Push API Container Image
      run: docker push liatriocorekjpoc.azurecr.io/liatriopocapi:1.0.${{ github.run_number }}
      
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'
      url: ${{ steps.deploy-to-apiapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App API
        id: deploy-to-apiapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APIAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_APIAPP_PUBLISH_PROFILE }}
          images: 'liatriocorekjpoc.azurecr.io/liatriopocapi:1.0.${{ github.run_number }}'
